config/routes.rb
ThaiAdmin::Application.routes.draw do
  resources :words
  resources :english_words
  resources :thai_words do 
    member do 
      get :audio
    end
  end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'admin/words#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/english_word.rb
class EnglishWord < Word
  def fetch
    doc = open("http://www.thai2english.com/dictionary/#{CGI::escape(self.word)}.html"){ |f| Hpricot(f) }
    (doc/".MainMeaningEng/.thai").each do |meaning_div|
      self.meaning += meaning_div.inner_html.clean_up.gsub(" ", "").split_up
    end
    self.meaning.uniq!

    (doc/"#reverseSearchLoading/.stripeMe").each do |r_div|
      r_word = r_div["word"].clean_up
      r_meaning = (r_div/"table//td").inner_html.clean_up.split_up
      self.reverse_examples[r_word] = r_meaning
    end
    self.save
    self
  end
end

app/models/thai_word.rb
class ThaiWord < Word
  def fetch
    doc = open("http://www.thai2english.com/search.aspx?q=#{CGI::escape(self.word)}"){ |f| Hpricot(f) }
    (doc/".thaiMeaningLi").each do |meaning_div|
      self.meaning += meaning_div.inner_html.clean_up.split_up
    end
    self.meaning.uniq!
    
    self.pronounciation = (doc/"#dictionaryTransliteration").inner_html.clean_up
    
    (doc/".examplesContainer/.stripeMe").each do |e_div|
      # raise e_div.inspect
      e_word = (e_div/"a.t2e/").to_html.clean_up
      e_meaning = (e_div/".floatedMeanings/ul/li").inner_html.clean_up.split_up
      self.examples[e_word] = e_meaning
    end

    (doc/"#reverseSearchLoading/.lineMeanings").each do |r_div|
      r_word = (r_div/"a.t2e_eng").inner_html.strip
      r_meaning = (r_div/"span.thai").inner_html.clean_up.split_up
      self.reverse_examples[r_word] = r_meaning
    end

    (doc/".soundalikesContainer/.stripeMe").each do |s_div|
      s_word = (s_div/"a.t2e").inner_html.strip
      s_meaning = []
      (s_div/"//.floatedMeanings/ul/li").each do |m|
        s_meaning += m.inner_html.clean_up.split_up
      end
      self.similar_words[s_word] = s_meaning
    end
    self.save
    self
  end
end

app/models/word.rb
# encoding: utf-8

class Word < ActiveRecord::Base
  serialize :examples, Hash
  serialize :reverse_examples, Hash
  serialize :meaning, Array
  serialize :similar_words, Hash
  validates_uniqueness_of :word
  paginates_per 30
  
  require 'open-uri'
  before_create :assign_type
  after_create :assign_details
  
  scope :thai, where(:type => "ThaiWord")
  scope :english, where(:type => "EnglishWord")
  scope :completed, where(:is_done => true).order("updated_at ASC")
  scope :to_be_completed, where(:is_done => false)
  scope :by_frequency, order("frequency DESC").where(:is_done => false)
  scope :by_random, order("RANDOM()").where(:is_done => false)
  
  def get_freq
    self.frequency = google_count(self.word)
    logger.error(self.frequency)
    self.save
    self
  end

  def assign_details
    Word.find(self.id).reset_content.fetch.get_freq
  end
  
  protected
  def assign_type
    if self.word.match(/[a-zA-Z]+/)
      self.type = "EnglishWord"
    else
      self.type = "ThaiWord"
    end
  end
  
  

  
  def reset_content
    self.word.strip!
    self.meaning = Array.new
    self.examples = Hash.new
    self.reverse_examples = Hash.new
    self.similar_words = Hash.new
    self
  end

  



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/english_words_controller.rb
class EnglishWordsController < InheritedResources::Base
  respond_to :html, :xml, :json
end

app/controllers/thai_words_controller.rb
class ThaiWordsController < InheritedResources::Base
  respond_to :html, :xml, :json
  has_scope :to_be_completed
  has_scope :completed
  has_scope :by_frequency
  has_scope :by_random
  
  def collection
    end_of_association_chain.order("created_at DESC").page(params[:page] || 1)
  end

  def audio
    text = CGI.escape(resource.word)
    url = "http://translate.google.com/translate_tts?tl=th&q=#{text}"
    response = open(url,
      {"User-Agent" => "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_4) AppleWebKit/536.5 (KHTML, like Gecko) Chrome/19.0.1084.56 Safari/536.5"}).read
    send_data response, :content_type => "audio/mpeg"
  end
  
  
end

app/controllers/words_controller.rb
class WordsController < InheritedResources::Base
  respond_to :html, :xml, :json



end

app/helpers/application_helper.rb
module ApplicationHelper
  # def tts(text, language = "en")
  #   url ="http://translate.google.com/translate_tts?tl=#{language}&q=#{URI.escape(text)}"
  #   data = ActiveSupport::Base64.encode64(open(url) { |io| io.read })
  #   raw "<audio controls=\"controls\" src=\"data:audio/mpeg;base64,#{data}\"></audio>"
  # end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ThaiAdmin</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing word</h1>

<%= render 'form' %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<h1>Listing words</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @words.each do |word| %>
  <tr>
    <td><%= link_to 'Show', word %></td>
    <td><%= link_to 'Edit', edit_word_path(word) %></td>
    <td><%= link_to 'Destroy', word, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Word', new_word_path %>

app/views/words/new.html.erb
<h1>New word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>